pipeline{
    agent any
    tools {
        terraform 'terraform-01'
    }

    stages{
        stage("Git Checkout"){
            steps{
                git credentialsId: '9e43ada6-2b46-4fb5-ac2c-70aabd1678c2', url: 'https://github.com/msaidcevik/tf-jenkins.git'
            }
        }
        stage("terraform init"){
            steps{
                sh 'terraform init'
            }
        }
        stage("terraform action"){
            steps{
                echo 'Terraform action from the parameter is --> ${action}'
                sh 'terraform ${action} -auto-approve -no-color'
            }
        }
    }
}
